
#ifndef CSRS_H
#define CSRS_H

#include <platform.h>

// --------------------------------------
// ---------- M MODE CSRS ---------------
// --------------------------------------

#define MISA_MXL_OFF (XLEN_BYTES * 8 - 2)
#define MISA_MXL_LEN (2)
#define MISA_A_OFF (0)
#define MISA_A_LEN (1)
#define MISA_B_OFF (1)
#define MISA_B_LEN (1)
#define MISA_C_OFF (2)
#define MISA_C_LEN (1)
#define MISA_D_OFF (3)
#define MISA_D_LEN (1)
#define MISA_F_OFF (5)
#define MISA_F_LEN (1)
#define MISA_H_OFF (7)
#define MISA_H_LEN (1)
#define MISA_I_OFF (8)
#define MISA_I_LEN (1)
#define MISA_K_OFF (10)
#define MISA_K_LEN (1)
#define MISA_M_OFF (12)
#define MISA_M_LEN (1)
#define MISA_S_OFF (18)
#define MISA_S_LEN (1)
#define MISA_U_OFF (20)
#define MISA_U_LEN (1)
#define MISA_V_OFF (21)
#define MISA_V_LEN (1)

#define MVENDORID_OFFSET_OFF (0)
#define MVENDORID_OFFSET_LEN (7)
#define MVENDORID_BANK_OFF (7)
#define MVENDORID_BANK_LEN (25)

#define MSTATUS_SIE_OFF     (1)
#define MSTATUS_SIE_LEN     (1)
#define MSTATUS_MIE_OFF     (3)
#define MSTATUS_MIE_LEN     (1)
#define MSTATUS_SPIE_OFF    (5)
#define MSTATUS_SPIE_LEN    (1)
#define MSTATUS_UBE_OFF     (6)
#define MSTATUS_UBE_LEN     (1)
#define MSTATUS_MPIE_OFF    (7)
#define MSTATUS_MPIE_LEN    (1)
#define MSTATUS_SPP_OFF     (8)
#define MSTATUS_SPP_LEN     (1)
#define MSTATUS_VS_OFF      (9)
#define MSTATUS_VS_LEN      (2)
#define MSTATUS_MPP_OFF     (11)
#define MSTATUS_MPP_LEN     (2)
#define MSTATUS_FS_OFF      (13)
#define MSTATUS_FS_LEN      (2)
#define MSTATUS_XS_OFF      (15)
#define MSTATUS_XS_LEN      (2)
#define MSTATUS_MPRV_OFF    (17)
#define MSTATUS_MPRV_LEN    (1)
#define MSTATUS_SUM_OFF     (18)
#define MSTATUS_SUM_LEN     (1)
#define MSTATUS_MXR_OFF     (19)
#define MSTATUS_MXR_LEN     (1)
#define MSTATUS_TVM_OFF     (20)
#define MSTATUS_TVM_LEN     (1)
#define MSTATUS_TW_OFF      (21)
#define MSTATUS_TW_LEN      (1)
#define MSTATUS_TSR_OFF     (22)
#define MSTATUS_TSR_LEN     (1)
#define MSTATUS_UXL_OFF     (32)
#define MSTATUS_UXL_LEN     (2)
#define MSTATUS_SXL_OFF     (34)
#define MSTATUS_SXL_LEN     (2)
#define MSTATUS_SBE_OFF     (36)
#define MSTATUS_SBE_LEN     (1)
#define MSTATUS_MBE_OFF     (37)
#define MSTATUS_MBE_LEN     (1)
#define MSTATUS_GVA_OFF     (38)
#define MSTATUS_GVA_LEN     (1)
#define MSTATUS_MPV_OFF     (39)
#define MSTATUS_MPV_LEN     (1)
#define MSTATUS_SD_OFF      (XLEN_BYTES * 8 - 1)
#define MSTATUS_SD_LEN      (1)

#define MTVEC_MODE_OFF     (0)
#define MTVEC_MODE_LEN     (2)
#define MTVEC_BASE_OFF     (2)
#define MTVEC_BASE_LEN     (XLEN_BYTES * 8 - 2)

#define MIDELEG_SSI_OFF     (1)
#define MIDELEG_SSI_LEN     (1)
#define MIDELEG_VSSI_OFF    (2)
#define MIDELEG_VSSI_LEN    (1)
#define MIDELEG_STI_OFF     (5)
#define MIDELEG_STI_LEN     (1)
#define MIDELEG_VSTI_OFF    (6)
#define MIDELEG_VSTI_LEN    (1)
#define MIDELEG_SEI_OFF     (9)
#define MIDELEG_SEI_LEN     (1)
#define MIDELEG_VSEI_OFF    (10)
#define MIDELEG_VSEI_LEN    (1)
#define MIDELEG_SGEI_OFF    (12)
#define MIDELEG_SGEI_LEN    (1)

#define MIP_SSIP_OFF    (1)
#define MIP_SSIP_LEN    (1)
#define MIP_VSSIP_OFF   (2)
#define MIP_VSSIP_LEN   (1)
#define MIP_MSIP_OFF    (3)
#define MIP_MSIP_LEN    (1)
#define MIP_STIP_OFF    (5)
#define MIP_STIP_LEN    (1)
#define MIP_VSTIP_OFF   (6)
#define MIP_VSTIP_LEN   (1)
#define MIP_MTIP_OFF    (7)
#define MIP_MTIP_LEN    (1)
#define MIP_SEIP_OFF    (9)
#define MIP_SEIP_LEN    (1)
#define MIP_VSEIP_OFF   (10)
#define MIP_VSEIP_LEN   (1)
#define MIP_MEIP_OFF    (11)
#define MIP_MEIP_LEN    (1)
#define MIP_SGEIP_OFF   (12)
#define MIP_SGEIP_LEN   (1)
#define MIP_LCOFIP_OFF  (13)
#define MIP_LCOFIP_LEN  (1)

#define MIE_SSIE_OFF    (1)
#define MIE_SSIE_LEN    (1)
#define MIE_VSSIE_OFF   (2)
#define MIE_VSSIE_LEN   (1)
#define MIE_MSIE_OFF    (3)
#define MIE_MSIE_LEN    (1)
#define MIE_STIE_OFF    (5)
#define MIE_STIE_LEN    (1)
#define MIE_VSTIE_OFF   (6)
#define MIE_VSTIE_LEN   (1)
#define MIE_MTIE_OFF    (7)
#define MIE_MTIE_LEN    (1)
#define MIE_SEIE_OFF    (9)
#define MIE_SEIE_LEN    (1)
#define MIE_VSEIE_OFF   (10)
#define MIE_VSEIE_LEN   (1)
#define MIE_MEIE_OFF    (11)
#define MIE_MEIE_LEN    (1)
#define MIE_SGEIE_OFF   (12)
#define MIE_SGEIE_LEN   (1)
#define MIE_LCOFIE_OFF  (13)
#define MIE_LCOFIE_LEN  (1)

#define MSTATEEN0_C_OFF         (0)
#define MSTATEEN0_C_LEN         (1)
#define MSTATEEN0_FCSR_OFF      (1)
#define MSTATEEN0_FCSR_LEN      (1)
#define MSTATEEN0_JVT_OFF       (2)
#define MSTATEEN0_JVT_LEN       (1)
#define MSTATEEN0_CTR_OFF       (54)
#define MSTATEEN0_CTR_LEN       (1)
#define MSTATEEN0_SRMCFG_OFF    (55)
#define MSTATEEN0_SRMCFG_LEN    (1)
#define MSTATEEN0_P1P13_OFF     (56)
#define MSTATEEN0_P1P13_LEN     (1)
#define MSTATEEN0_CONTEXT_OFF   (57)
#define MSTATEEN0_CONTEXT_LEN   (1)
#define MSTATEEN0_IMSIC_OFF     (58)
#define MSTATEEN0_IMSIC_LEN     (1)
#define MSTATEEN0_AIA_OFF       (59)
#define MSTATEEN0_AIA_LEN       (1)
#define MSTATEEN0_CSRIND_OFF    (60)
#define MSTATEEN0_CSRIND_LEN    (1)
#define MSTATEEN0_ENVCFG_OFF    (62)
#define MSTATEEN0_ENVCFG_LEN    (1)
#define MSTATEEN0_SE0_OFF       (63)
#define MSTATEEN0_SE0_LEN       (1)


// --------------------------------------
// ---------- S MODE CSRS ---------------
// --------------------------------------
#define SSTATUS_SIE_OFF     (1)
#define SSTATUS_SIE_LEN     (1)
#define SSTATUS_SPIE_OFF    (5)
#define SSTATUS_SPIE_LEN    (1)
#define SSTATUS_UBE_OFF     (6)
#define SSTATUS_UBE_LEN     (1)
#define SSTATUS_SPP_OFF     (8)
#define SSTATUS_SPP_LEN     (1)
#define SSTATUS_VS_OFF      (9)
#define SSTATUS_VS_LEN      (2)
#define SSTATUS_FS_OFF      (13)
#define SSTATUS_FS_LEN      (2)
#define SSTATUS_XS_OFF      (15)
#define SSTATUS_XS_LEN      (2)
#define SSTATUS_SUM_OFF     (18)
#define SSTATUS_SUM_LEN     (1)
#define SSTATUS_MXR_OFF     (19)
#define SSTATUS_MXR_LEN     (1)
#define SSTATUS_UXL_OFF     (32)
#define SSTATUS_UXL_LEN     (2)
#define SSTATUS_SD_OFF      (XLEN_BYTES * 8 - 1)
#define SSTATUS_SD_LEN      (1)

#define STVEC_MODE_OFF     (0)
#define STVEC_MODE_LEN     (2)
#define STVEC_BASE_OFF     (2)
#define STVEC_BASE_LEN     (XLEN_BYTES * 8 - 2)

#define SIP_SSIP_OFF    (1)
#define SIP_SSIP_LEN    (1)
#define SIP_VSSIP_OFF   (2)
#define SIP_VSSIP_LEN   (1)
#define SIP_STIP_OFF    (5)
#define SIP_STIP_LEN    (1)
#define SIP_VSTIP_OFF   (6)
#define SIP_VSTIP_LEN   (1)
#define SIP_SEIP_OFF    (9)
#define SIP_SEIP_LEN    (1)
#define SIP_VSEIP_OFF   (10)
#define SIP_VSEIP_LEN   (1)
#define SIP_LCOFIP_OFF  (13)
#define SIP_LCOFIP_LEN  (1)

#define SIE_SSIE_OFF    (1)
#define SIE_SSIE_LEN    (1)
#define SIE_VSSIE_OFF   (2)
#define SIE_VSSIE_LEN   (1)
#define SIE_STIE_OFF    (5)
#define SIE_STIE_LEN    (1)
#define SIE_VSTIE_OFF   (6)
#define SIE_VSTIE_LEN   (1)
#define SIE_SEIE_OFF    (9)
#define SIE_SEIE_LEN    (1)
#define SIE_VSEIE_OFF   (10)
#define SIE_VSEIE_LEN   (1)
#define SIE_LCOFIE_OFF  (13)
#define SIE_LCOFIE_LEN  (1)

#if XLEN_BYTES == 8  
#define SATP_PPN_OFF   (0)
#define SATP_PPN_LEN   (44)
#define SATP_ASID_OFF  (44)
#define SATP_ASID_LEN  (16)
#define SATP_MODE_OFF  (60)
#define SATP_MODE_LEN  (4)
#else
#define SATP_PPN_OFF   (0)
#define SATP_PPN_LEN   (22)
#define SATP_ASID_OFF  (22)
#define SATP_ASID_LEN  (9)
#define SATP_MODE_OFF  (31)
#define SATP_MODE_LEN  (1)
#endif

#define SSTATEEN0_C_OFF         (0)
#define SSTATEEN0_C_LEN         (1)
#define SSTATEEN0_FCSR_OFF      (1)
#define SSTATEEN0_FCSR_LEN      (1)
#define SSTATEEN0_JVT_OFF       (2)
#define SSTATEEN0_JVT_LEN       (1)

// --------------------------------------
// ---------- H MODE CSRS ---------------
// --------------------------------------
#define HSTATUS_VSBE_OFF     (5)
#define HSTATUS_VSBE_LEN     (1)
#define HSTATUS_GVA_OFF      (6)
#define HSTATUS_GVA_LEN      (1)
#define HSTATUS_SPV_OFF      (7)
#define HSTATUS_SPV_LEN      (1)
#define HSTATUS_SPVP_OFF     (8)
#define HSTATUS_SPVP_LEN     (1)
#define HSTATUS_HU_OFF       (9)
#define HSTATUS_HU_LEN       (1)
#define HSTATUS_VGEIN_OFF    (12)
#define HSTATUS_VGEIN_LEN    (6)
#define HSTATUS_VTVM_OFF     (20)
#define HSTATUS_VTVM_LEN     (1)
#define HSTATUS_VTW_OFF      (21)
#define HSTATUS_VTW_LEN      (1)
#define HSTATUS_VTSR_OFF     (22)
#define HSTATUS_VTSR_LEN     (1)
#define HSTATUS_VSXL_OFF     (32)
#define HSTATUS_VSXL_LEN     (2)

#define HIDELEG_SSI_OFF     (1)
#define HIDELEG_SSI_LEN     (1)
#define HIDELEG_VSSI_OFF    (2)
#define HIDELEG_VSSI_LEN    (1)
#define HIDELEG_STI_OFF     (5)
#define HIDELEG_STI_LEN     (1)
#define HIDELEG_VSTI_OFF    (6)
#define HIDELEG_VSTI_LEN    (1)
#define HIDELEG_SEI_OFF     (9)
#define HIDELEG_SEI_LEN     (1)
#define HIDELEG_VSEI_OFF    (10)
#define HIDELEG_VSEI_LEN    (1)

#define HVIP_VSSIP_OFF    (2)
#define HVIP_VSSIP_LEN    (1)
#define HVIP_VSTIP_OFF    (6)
#define HVIP_VSTIP_LEN    (1)
#define HVIP_VSEIP_OFF    (10)
#define HVIP_VSEIP_LEN    (1)

#define HIP_VSSIP_OFF    (2)
#define HIP_VSSIP_LEN    (1)
#define HIP_VSTIP_OFF    (6)
#define HIP_VSTIP_LEN    (1)
#define HIP_VSEIP_OFF    (10)
#define HIP_VSEIP_LEN    (1)
#define HIP_SGEIP_OFF    (12)
#define HIP_SGEIP_LEN    (1)

#define HIE_VSSIE_OFF    (2)
#define HIE_VSSIE_LEN    (1)
#define HIE_VSTIE_OFF    (6)
#define HIE_VSTIE_LEN    (1)
#define HIE_VSEIE_OFF    (10)
#define HIE_VSEIE_LEN    (1)
#define HIE_SGEIE_OFF    (12)
#define HIE_SGEIE_LEN    (1)

#define HSTATEEN0_C_OFF         (0)
#define HSTATEEN0_C_LEN         (1)
#define HSTATEEN0_FCSR_OFF      (1)
#define HSTATEEN0_FCSR_LEN      (1)
#define HSTATEEN0_JVT_OFF       (2)
#define HSTATEEN0_JVT_LEN       (1)
#define HSTATEEN0_CTR_OFF       (54)
#define HSTATEEN0_CTR_LEN       (1)
#define HSTATEEN0_CONTEXT_OFF   (57)
#define HSTATEEN0_CONTEXT_LEN   (1)
#define HSTATEEN0_IMSIC_OFF     (58)
#define HSTATEEN0_IMSIC_LEN     (1)
#define HSTATEEN0_AIA_OFF       (59)
#define HSTATEEN0_AIA_LEN       (1)
#define HSTATEEN0_CSRIND_OFF    (60)
#define HSTATEEN0_CSRIND_LEN    (1)
#define HSTATEEN0_ENVCFG_OFF    (62)
#define HSTATEEN0_ENVCFG_LEN    (1)
#define HSTATEEN0_SE0_OFF       (63)
#define HSTATEEN0_SE0_LEN       (1)

// --------------------------------------
// ---------- VS MODE CSRS --------------
// --------------------------------------
#define VSSTATUS_SIE_OFF     (1)
#define VSSTATUS_SIE_LEN     (1)
#define VSSTATUS_SPIE_OFF    (5)
#define VSSTATUS_SPIE_LEN    (1)
#define VSSTATUS_UBE_OFF     (6)
#define VSSTATUS_UBE_LEN     (1)
#define VSSTATUS_SPP_OFF     (8)
#define VSSTATUS_SPP_LEN     (1)
#define VSSTATUS_VS_OFF      (9)
#define VSSTATUS_VS_LEN      (2)
#define VSSTATUS_FS_OFF      (13)
#define VSSTATUS_FS_LEN      (2)
#define VSSTATUS_XS_OFF      (15)
#define VSSTATUS_XS_LEN      (2)
#define VSSTATUS_SUM_OFF     (18)
#define VSSTATUS_SUM_LEN     (1)
#define VSSTATUS_MXR_OFF     (19)
#define VSSTATUS_MXR_LEN     (1)
#define VSSTATUS_UXL_OFF     (32)
#define VSSTATUS_UXL_LEN     (2)
#define VSSTATUS_SD_OFF      (XLEN_BYTES * 8 - 1)
#define VSSTATUS_SD_LEN      (1)

#define VSTVEC_MODE_OFF     (0)
#define VSTVEC_MODE_LEN     (2)
#define VSTVEC_BASE_OFF     (2)
#define VSTVEC_BASE_LEN     (XLEN_BYTES * 8 - 2)

#define VSIP_SSIP_OFF    (1)
#define VSIP_SSIP_LEN    (1)
#define VSIP_STIP_OFF    (5)
#define VSIP_STIP_LEN    (1)
#define VSIP_SEIP_OFF    (9)
#define VSIP_SEIP_LEN    (1)
#define VSIP_LCOFIP_OFF  (13)
#define VSIP_LCOFIP_LEN  (1)

#define VSIE_SSIE_OFF    (1)
#define VSIE_SSIE_LEN    (1)
#define VSIE_STIE_OFF    (5)
#define VSIE_STIE_LEN    (1)
#define VSIE_SEIE_OFF    (9)
#define VSIE_SEIE_LEN    (1)
#define VSIE_LCOFIE_OFF  (13)
#define VSIE_LCOFIE_LEN  (1)

#if XLEN_BYTES == 8  
#define VSATP_PPN_OFF   (0)
#define VSATP_PPN_LEN   (44)
#define VSATP_ASID_OFF  (44)
#define VSATP_ASID_LEN  (16)
#define VSATP_MODE_OFF  (60)
#define VSATP_MODE_LEN  (4)
#else
#define VSATP_PPN_OFF   (0)
#define VSATP_PPN_LEN   (22)
#define VSATP_ASID_OFF  (22)
#define VSATP_ASID_LEN  (9)
#define VSATP_MODE_OFF  (31)
#define VSATP_MODE_LEN  (1)
#endif

#endif /* __ARCH_CSRS_H__ */
